MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

MethodName:
  EnforcedStyle: snake_case

AccessorMethodName:
  Description: Check the naming of accessor methods for get_/set_.
  Enabled: false

Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: true

HashSyntax:
  Description: >-
                 Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax
                 { :a => 1, :b => 2 }.
  Enabled: false
  EnforcedStyle: hash_rockets

LineEndConcatenation:
  Description: 'Use \\ instead of + to concatenate two string literals at line end.'
  Enabled: true
  
LineLength:
  Description: 'Limit lines to 79 characters.'
  Enabled: true
  Max: 80